export enum TaskEnum {
  CompleteProfileSetup = "Complete Profile Setup",
  ReferAFriend = "Refer a Friend",
  CompleteSmallTask = "Complete a Small Task",
  CompleteMediumTask = "Complete a Medium Task",
  CompleteLargeTask = "Complete a Large Task",
  ParticipateInForumDiscussions = "Participate in Forum Discussions",
  ProvideFeedbackOrBugReport = "Provide Feedback or Bug Report",
  FollowOfficialTwitterAccount = "Follow Official Twitter Account",
  RetweetAPost = "Retweet a Post",
  UsePlatformHashtagsInPosts = "Use Platform Hashtags in Posts",
  ParticipateInSocialMediaChallenges = "Participate in Social Media Challenges",
  WriteReviewOrTestimonial = "Write a Review or Testimonial",
  CreateAndShareOriginalContent = "Create and Share Original Content",
  JoinDiscordCommunity = "Join the Discord Community",
  ParticipateInCommunityDiscussions = "Participate in Community Discussions",
  HostCommunityCall = "Host a Community Call",
  AttendCommunityCall = "Attend a Community Call",
}
